### ISSUE TITLE
Jade file compiling without HTML ids and classes.

### ISSUE THREAD

**Issue by pmichalik85** [oroce/gulp-jade-php#2]
I don't know the reason but when i save my jade template all classes id or orther atributes dissapear in php i'm compiling to.

**Comment by oroce** [comment]
Could you send the output of:
`npm ls`
and 
`npm --version`

**Comment by pmichalik85** [comment]
npm ls:

Blank-Gulp-Jade-Compass-Sass-Template-WordPress-Theme@0.0.2 /Users/Egoist/Sites/fpp2/wp-content/themes/wordpress-jade-template-master
├─┬ bower@1.3.12
│ ├── abbrev@1.0.5
│ ├── archy@0.0.2
│ ├─┬ bower-config@0.5.2
│ │ ├── graceful-fs@2.0.3
│ │ ├─┬ optimist@0.6.1
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.2
│ │ └── osenv@0.0.3
│ ├── bower-endpoint-parser@0.2.2
│ ├─┬ bower-json@0.4.0
│ │ ├── deep-extend@0.2.11
│ │ ├── graceful-fs@2.0.3
│ │ └── intersect@0.0.3
│ ├── bower-logger@0.2.2
│ ├─┬ bower-registry-client@0.2.1
│ │ ├── async@0.2.10
│ │ ├── graceful-fs@2.0.3
│ │ ├── lru-cache@2.3.1
│ │ ├── mkdirp@0.3.5
│ │ ├─┬ request@2.27.0
│ │ │ ├── aws-sign@0.3.0
│ │ │ ├── cookie-jar@0.3.0
│ │ │ ├── forever-agent@0.5.2
│ │ │ ├─┬ form-data@0.1.4
│ │ │ │ ├── async@0.9.0
│ │ │ │ └─┬ combined-stream@0.0.7
│ │ │ │   └── delayed-stream@0.0.5
│ │ │ ├─┬ hawk@1.0.0
│ │ │ │ ├── boom@0.4.2
│ │ │ │ ├── cryptiles@0.2.2
│ │ │ │ ├── hoek@0.9.1
│ │ │ │ └── sntp@0.2.4
│ │ │ ├─┬ http-signature@0.10.0
│ │ │ │ ├── asn1@0.1.11
│ │ │ │ ├── assert-plus@0.1.2
│ │ │ │ └── ctype@0.5.2
│ │ │ ├── json-stringify-safe@5.0.0
│ │ │ ├── mime@1.2.11
│ │ │ ├── node-uuid@1.4.1
│ │ │ ├── oauth-sign@0.3.0
│ │ │ ├── qs@0.6.6
│ │ │ └── tunnel-agent@0.3.0
│ │ └── request-replay@0.2.0
│ ├─┬ cardinal@0.4.0
│ │ └─┬ redeyed@0.4.4
│ │   └── esprima@1.0.4
│ ├─┬ chalk@0.5.0
│ │ ├── ansi-styles@1.1.0
│ │ ├── escape-string-regexp@1.0.2
│ │ ├─┬ has-ansi@0.1.0
│ │ │ └── ansi-regex@0.2.1
│ │ ├─┬ strip-ansi@0.3.0
│ │ │ └── ansi-regex@0.2.1
│ │ └── supports-color@0.2.0
│ ├── chmodr@0.1.0
│ ├─┬ decompress-zip@0.0.8
│ │ ├─┬ binary@0.3.0
│ │ │ ├── buffers@0.1.1
│ │ │ └─┬ chainsaw@0.1.0
│ │ │   └── traverse@0.3.9
│ │ ├── mkpath@0.1.0
│ │ ├── nopt@2.2.1
│ │ ├─┬ readable-stream@1.1.13
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.31
│ │ └─┬ touch@0.0.2
│ │   └── nopt@1.0.10
│ ├─┬ fstream@1.0.2
│ │ └── inherits@2.0.1
│ ├─┬ fstream-ignore@1.0.1
│ │ ├── inherits@2.0.1
│ │ └─┬ minimatch@1.0.0
│ │   └── sigmund@1.0.0
│ ├─┬ glob@4.0.6
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@1.0.0
│ │ │ └── sigmund@1.0.0
│ │ └─┬ once@1.3.1
│ │   └── wrappy@1.0.1
│ ├── graceful-fs@3.0.4
│ ├─┬ handlebars@2.0.0
│ │ ├─┬ optimist@0.3.7
│ │ │ └── wordwrap@0.0.2
│ │ └─┬ uglify-js@2.3.6
│ │   ├── async@0.2.10
│ │   └─┬ source-map@0.1.40
│ │     └── amdefine@0.1.0
│ ├─┬ inquirer@0.7.1
│ │ ├─┬ cli-color@0.3.2
│ │ │ ├── d@0.1.1
│ │ │ ├─┬ es5-ext@0.10.4
│ │ │ │ ├── es6-iterator@0.1.1
│ │ │ │ └── es6-symbol@0.1.1
│ │ │ ├─┬ memoizee@0.3.8
│ │ │ │ ├─┬ es6-weak-map@0.1.2
│ │ │ │ │ ├── es6-iterator@0.1.1
│ │ │ │ │ └── es6-symbol@0.1.1
│ │ │ │ ├── event-emitter@0.3.1
│ │ │ │ ├── lru-queue@0.1.0
│ │ │ │ └── next-tick@0.2.2
│ │ │ └─┬ timers-ext@0.1.0
│ │ │   └── next-tick@0.2.2
│ │ ├── figures@1.3.3
│ │ ├── lodash@2.4.1
│ │ ├── mute-stream@0.0.4
│ │ ├─┬ readline2@0.1.0
│ │ │ └─┬ chalk@0.4.0
│ │ │   ├── ansi-styles@1.0.0
│ │ │   ├── has-color@0.1.7
│ │ │   └── strip-ansi@0.1.1
│ │ ├── rx@2.3.14
│ │ └── through@2.3.6
│ ├─┬ insight@0.4.3
│ │ ├── async@0.9.0
│ │ ├─┬ chalk@0.5.1
│ │ │ ├── ansi-styles@1.1.0
│ │ │ ├── escape-string-regexp@1.0.2
│ │ │ ├─┬ has-ansi@0.1.0
│ │ │ │ └── ansi-regex@0.2.1
│ │ │ ├─┬ strip-ansi@0.3.0
│ │ │ │ └── ansi-regex@0.2.1
│ │ │ └── supports-color@0.2.0
│ │ ├─┬ configstore@0.3.1
│ │ │ ├─┬ js-yaml@3.0.2
│ │ │ │ ├─┬ argparse@0.1.15
│ │ │ │ │ ├── underscore@1.4.4
│ │ │ │ │ └── underscore.string@2.3.3
│ │ │ │ └── esprima@1.0.4
│ │ │ ├── object-assign@0.3.1
│ │ │ └── uuid@1.4.2
│ │ ├─┬ inquirer@0.6.0
│ │ │ ├─┬ cli-color@0.3.2
│ │ │ │ ├── d@0.1.1
│ │ │ │ ├─┬ es5-ext@0.10.4
│ │ │ │ │ ├── es6-iterator@0.1.1
│ │ │ │ │ └── es6-symbol@0.1.1
│ │ │ │ ├─┬ memoizee@0.3.8
│ │ │ │ │ ├─┬ es6-weak-map@0.1.2
│ │ │ │ │ │ ├── es6-iterator@0.1.1
│ │ │ │ │ │ └── es6-symbol@0.1.1
│ │ │ │ │ ├── event-emitter@0.3.1
│ │ │ │ │ ├── lru-queue@0.1.0
│ │ │ │ │ └── next-tick@0.2.2
│ │ │ │ └─┬ timers-ext@0.1.0
│ │ │ │   └── next-tick@0.2.2
│ │ │ ├── lodash@2.4.1
│ │ │ ├── mute-stream@0.0.4
│ │ │ ├─┬ readline2@0.1.0
│ │ │ │ └─┬ chalk@0.4.0
│ │ │ │   ├── ansi-styles@1.0.0
│ │ │ │   ├── has-color@0.1.7
│ │ │ │   └── strip-ansi@0.1.1
│ │ │ ├── rx@2.3.14
│ │ │ └── through@2.3.6
│ │ ├─┬ lodash.debounce@2.4.1
│ │ │ ├── lodash.isfunction@2.4.1
│ │ │ ├─┬ lodash.isobject@2.4.1
│ │ │ │ └── lodash._objecttypes@2.4.1
│ │ │ └─┬ lodash.now@2.4.1
│ │ │   └── lodash._isnative@2.4.1
│ │ ├── object-assign@1.0.0
│ │ ├─┬ os-name@1.0.1
│ │ │ ├── minimist@1.1.0
│ │ │ └── osx-release@1.0.0
│ │ └─┬ tough-cookie@0.12.1
│ │   └── punycode@1.3.2
│ ├── is-root@1.0.0
│ ├── junk@1.0.0
│ ├── lockfile@1.0.0
│ ├── lru-cache@2.5.0
│ ├─┬ mkdirp@0.5.0
│ │ └── minimist@0.0.8
│ ├── mout@0.9.1
│ ├── nopt@3.0.1
│ ├── opn@1.0.0
│ ├── osenv@0.1.0
│ ├─┬ p-throttler@0.1.0
│ │ └── q@0.9.7
│ ├─┬ promptly@0.2.0
│ │ └─┬ read@1.0.5
│ │   └── mute-stream@0.0.4
│ ├── q@1.0.1
│ ├─┬ request@2.42.0
│ │ ├── aws-sign2@0.5.0
│ │ ├─┬ bl@0.9.3
│ │ │ └─┬ readable-stream@1.0.33
│ │ │   ├── core-util-is@1.0.1
│ │ │   ├── inherits@2.0.1
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10.31
│ │ ├── caseless@0.6.0
│ │ ├── forever-agent@0.5.2
│ │ ├─┬ form-data@0.1.4
│ │ │ ├── async@0.9.0
│ │ │ ├─┬ combined-stream@0.0.7
│ │ │ │ └── delayed-stream@0.0.5
│ │ │ └── mime@1.2.11
│ │ ├─┬ hawk@1.1.1
│ │ │ ├── boom@0.4.2
│ │ │ ├── cryptiles@0.2.2
│ │ │ ├── hoek@0.9.1
│ │ │ └── sntp@0.2.4
│ │ ├─┬ http-signature@0.10.0
│ │ │ ├── asn1@0.1.11
│ │ │ ├── assert-plus@0.1.2
│ │ │ └── ctype@0.5.2
│ │ ├── json-stringify-safe@5.0.0
│ │ ├── mime-types@1.0.2
│ │ ├── node-uuid@1.4.1
│ │ ├── oauth-sign@0.4.0
│ │ ├── qs@1.2.2
│ │ ├── stringstream@0.0.4
│ │ ├─┬ tough-cookie@0.12.1
│ │ │ └── punycode@1.3.2
│ │ └── tunnel-agent@0.4.0
│ ├─┬ request-progress@0.3.0
│ │ └── throttleit@0.0.2
│ ├── retry@0.6.0
│ ├── rimraf@2.2.8
│ ├── semver@2.3.2
│ ├─┬ shell-quote@1.4.2
│ │ ├── array-filter@0.0.1
│ │ ├── array-map@0.0.0
│ │ ├── array-reduce@0.0.0
│ │ └── jsonify@0.0.0
│ ├── stringify-object@1.0.0
│ ├─┬ tar-fs@0.5.2
│ │ ├─┬ pump@0.3.5
│ │ │ ├─┬ end-of-stream@1.0.0
│ │ │ │ └─┬ once@1.3.1
│ │ │ │   └── wrappy@1.0.1
│ │ │ └── once@1.2.0
│ │ └─┬ tar-stream@0.4.7
│ │   ├── bl@0.9.3
│ │   ├─┬ end-of-stream@1.1.0
│ │   │ └─┬ once@1.3.1
│ │   │   └── wrappy@1.0.1
│ │   ├─┬ readable-stream@1.0.33
│ │   │ ├── core-util-is@1.0.1
│ │   │ ├── inherits@2.0.1
│ │   │ ├── isarray@0.0.1
│ │   │ └── string_decoder@0.10.31
│ │   └── xtend@4.0.0
│ ├── tmp@0.0.23
│ ├─┬ update-notifier@0.2.0
│ │ ├─┬ configstore@0.3.1
│ │ │ ├─┬ js-yaml@3.0.2
│ │ │ │ ├─┬ argparse@0.1.15
│ │ │ │ │ ├── underscore@1.4.4
│ │ │ │ │ └── underscore.string@2.3.3
│ │ │ │ └── esprima@1.0.4
│ │ │ ├── object-assign@0.3.1
│ │ │ └── uuid@1.4.2
│ │ ├─┬ latest-version@0.2.0
│ │ │ └─┬ package-json@0.2.0
│ │ │   ├─┬ got@0.3.0
│ │ │   │ └── object-assign@0.3.1
│ │ │   └─┬ registry-url@0.1.1
│ │ │     └─┬ npmconf@2.1.1
│ │ │       ├─┬ config-chain@1.1.8
│ │ │       │ └── proto-list@1.2.3
│ │ │       ├── inherits@2.0.1
│ │ │       ├── ini@1.3.0
│ │ │       ├─┬ once@1.3.1
│ │ │       │ └── wrappy@1.0.1
│ │ │       └── uid-number@0.0.5
│ │ ├── semver-diff@0.1.0
│ │ └─┬ string-length@0.1.2
│ │   └─┬ strip-ansi@0.2.2
│ │     └── ansi-regex@0.1.0
│ └── which@1.0.5
├─┬ gulp@3.8.10
│ ├── archy@1.0.0
│ ├─┬ chalk@0.5.1
│ │ ├── ansi-styles@1.1.0
│ │ ├── escape-string-regexp@1.0.2
│ │ ├─┬ has-ansi@0.1.0
│ │ │ └── ansi-regex@0.2.1
│ │ ├─┬ strip-ansi@0.3.0
│ │ │ └── ansi-regex@0.2.1
│ │ └── supports-color@0.2.0
│ ├── deprecated@0.0.1
│ ├── interpret@0.3.7
│ ├─┬ liftoff@0.13.6
│ │ ├── extend@1.3.0
│ │ ├─┬ findup-sync@0.1.3
│ │ │ ├─┬ glob@3.2.11
│ │ │ │ ├── inherits@2.0.1
│ │ │ │ └─┬ minimatch@0.3.0
│ │ │ │   ├── lru-cache@2.5.0
│ │ │ │   └── sigmund@1.0.0
│ │ │ └── lodash@2.4.1
│ │ ├── flagged-respawn@0.3.1
│ │ └── resolve@1.0.0
│ ├── minimist@1.1.0
│ ├─┬ orchestrator@0.3.7
│ │ ├─┬ end-of-stream@0.1.5
│ │ │ └─┬ once@1.3.1
│ │ │   └── wrappy@1.0.1
│ │ ├── sequencify@0.0.7
│ │ └── stream-consume@0.1.0
│ ├── pretty-hrtime@0.2.2
│ ├── semver@4.1.0
│ ├─┬ tildify@1.0.0
│ │ └── user-home@1.1.0
│ ├── v8flags@1.0.1
│ └─┬ vinyl-fs@0.3.11
│   ├─┬ glob-stream@3.1.15
│   │ ├─┬ glob@4.0.6
│   │ │ ├── inherits@2.0.1
│   │ │ └─┬ once@1.3.1
│   │ │   └── wrappy@1.0.1
│   │ ├── glob2base@0.0.11
│   │ ├─┬ minimatch@1.0.0
│   │ │ ├── lru-cache@2.5.0
│   │ │ └── sigmund@1.0.0
│   │ ├── ordered-read-streams@0.0.8
│   │ └── unique-stream@1.0.0
│   ├─┬ glob-watcher@0.0.6
│   │ └─┬ gaze@0.5.1
│   │   └─┬ globule@0.1.0
│   │     ├─┬ glob@3.1.21
│   │     │ ├── graceful-fs@1.2.3
│   │     │ └── inherits@1.0.0
│   │     ├── lodash@1.0.1
│   │     └─┬ minimatch@0.2.14
│   │       ├── lru-cache@2.5.0
│   │       └── sigmund@1.0.0
│   ├── graceful-fs@3.0.4
│   ├── lodash@2.4.1
│   ├─┬ mkdirp@0.5.0
│   │ └── minimist@0.0.8
│   ├─┬ strip-bom@1.0.0
│   │ ├── first-chunk-stream@1.0.0
│   │ └── is-utf8@0.2.0
│   ├─┬ through2@0.6.3
│   │ ├─┬ readable-stream@1.0.33
│   │ │ ├── core-util-is@1.0.1
│   │ │ ├── inherits@2.0.1
│   │ │ ├── isarray@0.0.1
│   │ │ └── string_decoder@0.10.31
│   │ └── xtend@4.0.0
│   └─┬ vinyl@0.4.3
│     └── clone-stats@0.0.1
├─┬ gulp-compass@1.3.3
│ ├─┬ through2@0.6.3
│ │ ├─┬ readable-stream@1.0.33
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.31
│ │ └── xtend@4.0.0
│ └── which@1.0.5
├─┬ gulp-jade-php@1.0.0
│ ├─┬ jade-php@0.1.2
│ │ ├─┬ constantinople@3.0.1
│ │ │ └─┬ acorn-globals@1.0.1
│ │ │   └── acorn@0.8.0
│ │ └─┬ jade@0.35.0
│ │   ├── character-parser@1.2.0
│ │   ├── commander@2.0.0
│ │   ├─┬ constantinople@1.0.2
│ │   │ └─┬ uglify-js@2.4.15
│ │   │   ├── async@0.2.10
│ │   │   ├─┬ optimist@0.3.7
│ │   │   │ └── wordwrap@0.0.2
│ │   │   ├─┬ source-map@0.1.34
│ │   │   │ └── amdefine@0.1.0
│ │   │   └── uglify-to-browserify@1.0.2
│ │   ├── mkdirp@0.3.5
│ │   ├─┬ monocle@1.1.50
│ │   │ └─┬ readdirp@0.2.5
│ │   │   └─┬ minimatch@1.0.0
│ │   │     ├── lru-cache@2.5.0
│ │   │     └── sigmund@1.0.0
│ │   ├─┬ transformers@2.1.0
│ │   │ ├─┬ css@1.0.8
│ │   │ │ ├── css-parse@1.0.4
│ │   │ │ └── css-stringify@1.0.5
│ │   │ ├─┬ promise@2.0.0
│ │   │ │ └── is-promise@1.0.1
│ │   │ └─┬ uglify-js@2.2.5
│ │   │   ├─┬ optimist@0.3.7
│ │   │   │ └── wordwrap@0.0.2
│ │   │   └─┬ source-map@0.1.40
│ │   │     └── amdefine@0.1.0
│ │   └─┬ with@1.1.1
│ │     └─┬ uglify-js@2.4.0
│ │       ├── async@0.2.10
│ │       ├─┬ optimist@0.3.7
│ │       │ └── wordwrap@0.0.2
│ │       ├─┬ source-map@0.1.40
│ │       │ └── amdefine@0.1.0
│ │       └── uglify-to-browserify@1.0.2
│ └─┬ through2@0.5.1
│   ├─┬ readable-stream@1.0.33
│   │ ├── core-util-is@1.0.1
│   │ ├── inherits@2.0.1
│   │ ├── isarray@0.0.1
│   │ └── string_decoder@0.10.31
│   └── xtend@3.0.0
├─┬ gulp-plumber@0.6.6
│ └─┬ through2@0.6.3
│   ├─┬ readable-stream@1.0.33
│   │ ├── core-util-is@1.0.1
│   │ ├── inherits@2.0.1
│   │ ├── isarray@0.0.1
│   │ └── string_decoder@0.10.31
│   └── xtend@4.0.0
├─┬ gulp-util@3.0.1
│ ├─┬ chalk@0.5.1
│ │ ├── ansi-styles@1.1.0
│ │ ├── escape-string-regexp@1.0.2
│ │ ├─┬ has-ansi@0.1.0
│ │ │ └── ansi-regex@0.2.1
│ │ ├─┬ strip-ansi@0.3.0
│ │ │ └── ansi-regex@0.2.1
│ │ └── supports-color@0.2.0
│ ├── dateformat@1.0.8
│ ├── lodash@2.4.1
│ ├── lodash._reinterpolate@2.4.1
│ ├─┬ lodash.template@2.4.1
│ │ ├── lodash._escapestringchar@2.4.1
│ │ ├─┬ lodash.defaults@2.4.1
│ │ │ └── lodash._objecttypes@2.4.1
│ │ ├─┬ lodash.escape@2.4.1
│ │ │ ├─┬ lodash._escapehtmlchar@2.4.1
│ │ │ │ └── lodash._htmlescapes@2.4.1
│ │ │ └─┬ lodash._reunescapedhtml@2.4.1
│ │ │   └── lodash._htmlescapes@2.4.1
│ │ ├─┬ lodash.keys@2.4.1
│ │ │ ├── lodash._isnative@2.4.1
│ │ │ ├─┬ lodash._shimkeys@2.4.1
│ │ │ │ └── lodash._objecttypes@2.4.1
│ │ │ └─┬ lodash.isobject@2.4.1
│ │ │   └── lodash._objecttypes@2.4.1
│ │ ├── lodash.templatesettings@2.4.1
│ │ └── lodash.values@2.4.1
│ ├── minimist@1.1.0
│ ├─┬ multipipe@0.1.2
│ │ └─┬ duplexer2@0.0.2
│ │   └─┬ readable-stream@1.1.13
│ │     ├── core-util-is@1.0.1
│ │     ├── inherits@2.0.1
│ │     ├── isarray@0.0.1
│ │     └── string_decoder@0.10.31
│ ├─┬ through2@0.6.3
│ │ ├─┬ readable-stream@1.0.33
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.31
│ │ └── xtend@4.0.0
│ └─┬ vinyl@0.4.3
│   └── clone-stats@0.0.1
├─┬ gulp-watch@0.6.10
│ ├─┬ gaze@0.5.1
│ │ └─┬ globule@0.1.0
│ │   ├─┬ glob@3.1.21
│ │   │ ├── graceful-fs@1.2.3
│ │   │ └── inherits@1.0.0
│ │   ├── lodash@1.0.1
│ │   └─┬ minimatch@0.2.14
│ │     ├── lru-cache@2.5.0
│ │     └── sigmund@1.0.0
│ ├─┬ glob@4.0.6
│ │ ├── graceful-fs@3.0.4
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@1.0.0
│ │ │ ├── lru-cache@2.5.0
│ │ │ └── sigmund@1.0.0
│ │ └─┬ once@1.3.1
│ │   └── wrappy@1.0.1
│ ├─┬ glob2base@0.0.11
│ │ └── lodash@2.4.1
│ ├─┬ gulp-batch@0.4.1
│ │ └─┬ event-stream@3.1.7
│ │   ├── duplexer@0.1.1
│ │   ├── from@0.1.3
│ │   ├── map-stream@0.1.0
│ │   ├── pause-stream@0.0.11
│ │   ├── split@0.2.10
│ │   ├── stream-combiner@0.0.4
│ │   └── through@2.3.6
│ ├─┬ minimatch@0.4.0
│ │ ├── lru-cache@2.5.0
│ │ └── sigmund@1.0.0
│ ├─┬ vinyl@0.3.3
│ │ ├── clone-stats@0.0.1
│ │ └── lodash@2.4.1
│ └─┬ vinyl-fs@0.3.11
│   ├─┬ glob-stream@3.1.15
│   │ ├─┬ minimatch@1.0.0
│   │ │ ├── lru-cache@2.5.0
│   │ │ └── sigmund@1.0.0
│   │ ├── ordered-read-streams@0.0.8
│   │ └── unique-stream@1.0.0
│   ├── glob-watcher@0.0.6
│   ├── graceful-fs@3.0.4
│   ├── lodash@2.4.1
│   ├─┬ mkdirp@0.5.0
│   │ └── minimist@0.0.8
│   ├─┬ strip-bom@1.0.0
│   │ ├── first-chunk-stream@1.0.0
│   │ └── is-utf8@0.2.0
│   ├─┬ through2@0.6.3
│   │ ├─┬ readable-stream@1.0.33
│   │ │ ├── core-util-is@1.0.1
│   │ │ ├── inherits@2.0.1
│   │ │ ├── isarray@0.0.1
│   │ │ └── string_decoder@0.10.31
│   │ └── xtend@4.0.0
│   └─┬ vinyl@0.4.3
│     └── clone-stats@0.0.1
└─┬ jade@1.7.0
  ├── character-parser@1.2.0
  ├── commander@2.1.0
  ├─┬ constantinople@2.0.1
  │ └─┬ uglify-js@2.4.15
  │   ├── async@0.2.10
  │   ├─┬ optimist@0.3.7
  │   │ └── wordwrap@0.0.2
  │   ├─┬ source-map@0.1.34
  │   │ └── amdefine@0.1.0
  │   └── uglify-to-browserify@1.0.2
  ├─┬ mkdirp@0.5.0
  │ └── minimist@0.0.8
  ├─┬ monocle@1.1.51
  │ └─┬ readdirp@0.2.5
  │   └─┬ minimatch@1.0.0
  │     ├── lru-cache@2.5.0
  │     └── sigmund@1.0.0
  ├─┬ transformers@2.1.0
  │ ├─┬ css@1.0.8
  │ │ ├── css-parse@1.0.4
  │ │ └── css-stringify@1.0.5
  │ ├─┬ promise@2.0.0
  │ │ └── is-promise@1.0.1
  │ └─┬ uglify-js@2.2.5
  │   ├─┬ optimist@0.3.7
  │   │ └── wordwrap@0.0.2
  │   └─┬ source-map@0.1.40
  │     └── amdefine@0.1.0
  ├── void-elements@1.0.0
  └─┬ with@3.0.1
    └─┬ uglify-js@2.4.15
      ├── async@0.2.10
      ├─┬ optimist@0.3.7
      │ └── wordwrap@0.0.2
      ├─┬ source-map@0.1.34
      │ └── amdefine@0.1.0
      └── uglify-to-browserify@1.0.2

npm --version: 

1.4.3

**Comment by oroce** [comment]
as you can see, `jade-php@0.1.2` is installed (the latest one)

```
├─┬ gulp-jade-php@1.0.0
│ ├─┬ jade-php@0.1.2
```

So if you compile this:

```
a(href=test(), id!=test2(), data-teste="teste") Test
```

You should get this:

```
'<a href="<?php echo htmlspecialchars(test(), ENT_QUOTES, \'UTF-8\'); ?>" id="<?php echo test2(); ?>" data-teste="teste">Test</a>'
```

**Comment by pmichalik85** [comment]
unfortunately my output is Test string between a tags.. not really sure what could be the reason for that.

**Comment by ZoRDoK** [comment]
My problem too. It is because 0.1.2 version jade-php with broken "arguments parsing" feature. 

update:
my mistake. on project jade-php all ok

**Comment by ZoRDoK** [comment]
If you degrade to 0.1.1 or comment this functional in jade-php all will work good.

**Comment by ZoRDoK** [comment]
Oroce, if you add class to any tag in your tests, you see it yourself.

**Comment by ZoRDoK** [comment]
Identical tests for php-jade is work. I think it's a jade version problem (php-jade use 0.3.5, but 1.7.0 in your project)

**Comment by oroce** [comment]
I published `gulp-jade-php@1.1.0`, it uses `jade-php@0.1.1`.

Also I extended the layout test case (added class name, and class attribute to li element).

Please open an issue in [viniwrubleski/jade-php](https://github.com/viniwrubleski/jade-php). You can even submit my tests, which will fail.
