### ISSUE TITLE
js conditionals rendering as php

### ISSUE THREAD

**Issue by bkcummins** [oroce/gulp-jade-php#4]
If I do the basic conditional below in gulp-jade and gulp-jade-php i get two different results.

```
- var foo = {greetings:"bob"}
div
  | hello 
  if foo
    | #{foo.greetings}
  else
    | world
```

gulp-jade output:

```
<div>hello bob</div>
```

gulp-jade-php output:

```
<?php var foo = {greetings:"bob"} ?>
<div>hello<?php if ( foo) ?>foo.greetings<?php else ?>world</div>
```

How do you do js conditionals w gulp-jade-php?  

It seems like php conditionals should be written after "-" or "=".

Thx in advance!

**Comment by bkcummins** [comment]
inline conditional works

example

```
a(href=(field.url !== '')? field.url : undefined) #{ field.title }
```

**Comment by oroce** [comment]
actually I have no clue :(
this module just wraps [jade-php](https://github.com/viniwrubleski/jade-php).

You should ask there, you'll more likely get a better/more accurate answer.
